[package]
edition = "2024"
name = "notification"
publish = false
version = "0.1.0"


[features]
ai_tool = ["dep:ai_toolset", "dep:anyhow", "dep:async-trait", "dep:schemars"]
axum = [
  "dep:axum",
  "dep:macro_authorization",
  "dep:model-error-response",
  "dep:model_user",
  "models_pagination/axum",
  "schema",
]
docs = ["dep:aquamarine"]
redis-tests = []
schema = ["dep:utoipa", "macro_user_id/schema"]

[dependencies]
ai_toolset = { path = "../ai_toolset", optional = true }
anyhow = { workspace = true, optional = true }
aquamarine = { version = "0.6", optional = true }
async-trait = { workspace = true, optional = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-sns = { workspace = true }
aws-sdk-sqs = { workspace = true }
ses_client = { path = "../ses_client" }
axum = { workspace = true, optional = true }
broadcast = { path = "../broadcast" }
chrono = { workspace = true }
cowlike = { path = "../cowlike" }
either = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
itertools = { workspace = true }
kafka_util = { path = "../kafka_util" }
last_online_tracker = { path = "../last_online_tracker" }
macro_event_broker = { path = "../macro_event_broker" }
macro_event_topics = { path = "../macro_event_topics" }
macro_authorization = { path = "../macro_authorization", default-features = false, features = [
  "axum",
], optional = true }
macro_env = { path = "../macro_env" }
macro_service_urls = { path = "../macro_service_urls" }
macro_user_id = { path = "../macro_user_id" }
macro_uuid = { path = "../macro_uuid" }
model-entity = { path = "../model-entity" }
model-error-response = { path = "../model-error-response", optional = true }
model_user = { path = "../model_user", optional = true }
models_pagination = { path = "../models_pagination" }
rate_limit = { path = "../rate_limit" }
redis = { workspace = true, features = [
  "aio",
  "tokio-comp",
  "tokio-rustls-comp",
] }
rdkafka = { workspace = true }
reqwest = { workspace = true }
rootcause = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tokio-retry = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true, optional = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
http-body-util = { workspace = true }
macro_db_migrator = { path = "../macro_db_migrator" }
model_notifications = { path = "../model_notifications" }
rate_limit = { path = "../rate_limit", features = ["testing"] }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }
tower = { workspace = true }
