[package]
edition = "2024"
name = "macro_db_client"
publish = false
version = "0.1.0"

[features]
account_merge_request = ["dep:rand"]
default = ["account_merge_request", "team"]
team = ["dep:models_team"]

[dependencies]
agent = { path = "../agent" }
anyhow = { workspace = true }
async-recursion = "1.1.1"
async-trait = { workspace = true }
cached = { workspace = true }
chrono = { workspace = true }
document_sub_type = { path = "../document_sub_type" }
entity_access_db_utils = { path = "../entity_access_db_utils" }
futures = { workspace = true }
macro_env = { path = "../macro_env" }
macro_user_id = { path = "../macro_user_id" }
macro_uuid = { path = "../macro_uuid" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
model_file_type = { path = "../model_file_type" }
models_dcs = { path = "../models_dcs" }
models_entity_access_management = { path = "../models_entity_access_management", features = [
  "db",
] }
models_opensearch = { path = "../models_opensearch" }
models_pagination = { path = "../models_pagination" }
models_permissions = { path = "../models_permissions" }
models_team = { path = "../models_team", optional = true }
non_empty = { path = "../non_empty" }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
system_properties = { path = "../system_properties" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
user_quota = { path = "../user_quota" }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
